name: Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint nbqa
        python setup.py egg_info
        pip install -r *.egg-info/requires.txt
        pip install -r test-time-requirements.txt
    - name: Analysing the code with pylint
      run: |
        # TODO #299
        pylint --disable=fixme --max-module-lines=200 \
               --disable=too-many-locals,too-many-branches,duplicate-code,invalid-name,missing-function-docstring,missing-module-docstring,too-many-arguments,missing-class-docstring,too-many-instance-attributes $(git ls-files '*.py')
    - name: Analysing notebook code with pyling
      run: |
        # TODO #299
        nbqa pylint --disable=fixme,trailing-whitespace,wrong-import-position,ungrouped-imports\
                    --disable=duplicate-code,invalid-name,missing-module-docstring,line-too-long,missing-function-docstring,redefined-outer-name,too-many-arguments,no-member,too-many-locals,cell-var-from-loop,missing-class-docstring $(git ls-files '*.ipynb')
